resolve syntactic variable assignment error #1828
Rarely executed code: if a share was moved from
one pool to another between db updates, and the
db retrieval order of pools was appropriate. An
existing db share entry from a prior pool to
that under share import would be updated. However
this 'intended' update would fail due to a code
formatting issue resulting in the following
error: "ValueError: too many values to unpack".