disk serial=none or fake-serial re sda[a-z] dev names #1925
On systems with 27 or more disks named sd* where the system/root is also
installed on sda ie sda3 and where the 27th and subsequent disks are
named sdaa, sdab etc and are also btrfs formatted; a regex based serial
propagation bug (from base device to partition) in scan_disks() resulted
in the first listed (by lsblk) sda[a-z] device receiving a
serial=none attribution and the second and all subsequent listed
sda[a-z] devices receiving an erroneous fake-serial attribution. All
affected devices would also have empty (or incorrectly inherited from
sda) model, transport, vendor, and hctl attributions. This resulted in
an inability for the system to update the disk state as the abstracted
disk info from the corrupt parsing of attached disk state caused an
exception: "TypeError: expected string or buffer".

Note that all affected disks (sda[a-z]) were also miss attributed as
root=True in the erroneous abstract data produced by scan_disks()

Summary

1. Add scan_disks() test mode to enable repeatable fake-serial- tests.
2. Establish unit tests to reproduce the above issue, as reported (36
disk system) and as a minimum artificial drive subset.
3. Establish unit tests to identify current correct behaviour for system
disk on LUKS, mdraid, and bios mdraid; as well as btrfs in partition and
data disk on bios mdraid behaviour.
4. Fix overly broad regex to identify system disk partitions, if any:
ie improve system disk partition match mechanism.
5. Fix system disk LUKS, mdraid, bios mdraid regressions as a result of
(4).
6. Address pre-existing TODO: re mdraid info via model info on non
system disks; as part of the fix for (5).